### ISSUE TITLE
Login system and sessions

### ISSUE THREAD

**Issue by vaibhavmule** [Mindgreppers/lifemaker-backend#3]

**Comment by awesomepankaj** [comment]
We will use JWT.

Server will send a fresh JWT token to client on login. That token will be sent by the client to server, with every request. When the client logs out, the token will be deleted by the server.

client emits:
c>> login, username|password
s>>user.username.login.error: status|message
s>>user.username.login.done : jwt:"xxx"|user:{}
c>>user.username.logout: username, jwt
s>>user.username.logout.done: status:200|message:"successfully logged out"
s>>user.username.logout.error: status:400/500|message:""
